### ISSUE TITLE
Конфликт наложения THeroAction...Finish при повторном создании THeroAction... того же типа

### ISSUE THREAD

**Issue by GetLocalPlayer** [tereshenkovav/PonyRubyGrabber#4]
https://github.com/tereshenkovav/PonyRubyGrabber/blob/f80814623558e43756462905c0c4f53ebe10d901/src/core/scenegame.pas#L390

https://github.com/tereshenkovav/PonyRubyGrabber/blob/f80814623558e43756462905c0c4f53ebe10d901/src/core/scenegame.pas#L394

https://github.com/tereshenkovav/PonyRubyGrabber/blob/f80814623558e43756462905c0c4f53ebe10d901/src/core/scenegame.pas#L508

Добавление нового `THeroAction...` в список `active_actions` без проверки наличия уже действующей `THeroAction...` того же типа приводит к завершению действия всех `THeroAction...` этого типа в списке в момент завершения самого первого `THeroAction...` этого типа, поскольку часть поведения и данных объекта `THero` не изолировано и контролируется `TSceneGame` внутри вызова `FrameFunc`.

Варианты
**Просто:** проверить наличие `THeroAction...` того же типа перед его созданием, с обновлением времени действия уже существующего вместо создания нового.
**Сложно:** изолировать поведение `THero` в его методе `Update` и связанные с этим поведением поля, вызывать метод `Update` из `TSceneGame.FrameFunc`.

**Comment by tereshenkovav** [comment]
Исправлено простейшим образом, путем удаления предыдущего аналогичного действия перед добавлением нового.
https://github.com/tereshenkovav/PonyRubyGrabber/commit/639cb12bffa9ca77f6eab44f22cae656039ac41b
